### ISSUE TITLE
Curves aren't 'hide-able' on the Sensitivity tab

### ISSUE THREAD

**Issue by JDChallenger** [mrc-ide/wodin-shortcourse-2023#6]
I've noticed this on the Stochasticity practicals, on the Sensitivity tab. When plot type 'Value at a single time' is selected, you can't hide the curves in the normal way (i.e. by clicking on the legend marker). When you instead use plot type 'Trace over time', everything works perfectly.

**Comment by pwinskill** [comment]
Just to note, this isn't super-urgent as we cam work around it atm by using the "select variables" buttons at the bottom of the "Code" tab, but nice to have the option.

**Comment by richfitz** [comment]
This is fixed now
