### ISSUE TITLE
French button not disabled.

### ISSUE THREAD

**Issue by cm401** [mrc-ide/wodin-shortcourse-2023#7]
@richfitz French button available but doesn't toggle to French. Given that we will have a bunch of French speaker it might be better to remove/disable rather than confuse them. Thank you

<img width="331" alt="image" src="https://github.com/mrc-ide/wodin-shortcourse-2023/assets/26151931/580bf1c0-5927-456f-9f2e-a1f40536c3a0">

**Comment by richfitz** [comment]
Gone now!
